local Vector = require(script.Parent.Parent:WaitForChild("Vector"))

return function()
	-- describe("Vector", function()
	local a = Vector.new(3,1)
	local b = Vector.new(2,4)
	local a4 = Vector.new(1,2,3)
	local b4 = Vector.new(1,5,7)
	it("should add vectors", function()
		expect(a + b).to.equal(Vector.new(5,5))
	end)
	it("should subtract vectors", function()
		expect(a - b).to.equal(Vector.new(1,-3))
	end)
	it("should set magnitude", function()
		expect(math.round(100*a4.Magnitude)).to.equal(math.round(math.sqrt(14)*100))
	end)
	it("should multiply vectors", function()
		expect(a * b).to.equal(Vector.new(6,4))
	end)
	it("should multiply scalars", function()
		expect(a * 2).to.equal(Vector.new(6, 2))
	end)
	it("should divide vectors", function()
		expect((a / b):Round(1)).to.equal(Vector.new(3/2,1/4):Round(1))
	end)
	it("should divide scalars", function()
		expect(a / 2).to.equal(Vector.new(1.5, 0.5))
	end)
	it("should round", function()
		expect(Vector.new(1.2535363743, 0.00268370945):Round(2)).to.equal(Vector.new(1.25,0))
	end)
	it("should cross", function()
		expect((a4:Cross(b4)):Round(2)).to.equal(Vector.new(-1,-4,3))
	end)
	it("should dot", function()
		expect((a4:ScalarDot(b4))).to.equal(32)
	end)
	-- end)
end