[package]
name = "math2"
description = "A lua math library with some added features useful in Roblox game dev"
version = "1.0.0"
authors = ["CJ Oyer <coyer@nightcycle.us>"]
realm = "shared"
registry = "https://github.com/nightcycle/math2"
exclude = ["Packages", ".vscode"]

[dependencies]