[package]
name = "nightcycle/luau-math"
description = "A luau math library with various custom data types and utilities helpful in roblox dev."
version = "1.2.0"
authors = ["CJ Oyer <coyer@nightcycle.us>"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["Packages", ".vscode"]

[dependencies]
# graph = "nightcycle/boat-graph@^1.0.2"