[package]
name = "nightcycle/math"
description = "A lua math library with various custom data types and utilities helpful in roblox dev."
version = "3.5.5"
authors = ["CJ Oyer <coyer@nightcycle.us>"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["Packages", ".vscode"]

[dependencies]
graph = "nightcycle/boat-graph@^1.0.2"