local Vector = require(script.Parent:WaitForChild("Vector"))
local Matrix = require(script.Parent:WaitForChild("Matrix"))

return function()
	-- describe("Vector", function()
	local a = Vector.new(3,1)
	local b = Vector.new(2,4)
	it("should add vectors", function()
		expect(a + b).to.equal(Vector.new(5,5))
	end)
	it("should subtract vectors", function()
		expect(a - b).to.equal(Vector.new(1,-3))
	end)
	it("should multiply vectors", function()
		expect(a * b).to.equal(Vector.new(6,4))
	end)
	it("should multiply scalars", function()
		expect(a * 2).to.equal(Vector.new(6, 2))
	end)
	it("should divide vectors", function()
		expect((a / b):Round(1)).to.equal(Vector.new(3/2,1/4):Round(1))
	end)
	it("should divide scalars", function()
		expect(a / 2).to.equal(Vector.new(1.5, 0.5))
	end)
	it("should round", function()
		expect(Vector.new(1.2535363743, 0.00268370945):Round(2)).to.equal(Vector.new(1.25,0))
	end)
	-- end)
end